version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gsc4m6vjq2c4"
s3_prefix = "test"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
